create table if not exists intraday_posts (
  "id" bigint primary key,
  "date" text,
  "post_id" text,
  "filename" text,
  "centroid" double precision,
  "centroid_is_range" bigint,
  "centroid_source" text,
  "upside_pivot" double precision,
  "downside_pivot" double precision,
  "upside_target" double precision,
  "downside_target" double precision,
  "zero_vanna" double precision,
  "charm_flip" double precision,
  "pattern_type" text,
  "net_speed" text,
  "net_speed_slope_pct" double precision,
  "directional_bias" text,
  "SPX_close_prev" double precision,
  "SPX_center" double precision,
  "SPX_s1_upper" double precision,
  "SPX_s1_lower" double precision,
  "SPX_risk_upper" double precision,
  "SPX_risk_lower" double precision,
  "SPX_s2_upper" double precision,
  "SPX_s2_lower" double precision,
  "SPX_s3_upper" double precision,
  "SPX_s3_lower" double precision,
  "SPX_s1_pct" double precision,
  "SPX_s2_pct" double precision,
  "ES_close_prev" double precision,
  "ES_center" double precision,
  "ES_s1_upper" double precision,
  "ES_s1_lower" double precision,
  "ES_risk_upper" double precision,
  "ES_risk_lower" double precision,
  "ES_s2_upper" double precision,
  "ES_s2_lower" double precision,
  "ES_s3_upper" double precision,
  "ES_s3_lower" double precision,
  "ES_s1_pct" double precision,
  "ES_s2_pct" double precision,
  "SPY_close_prev" double precision,
  "SPY_center" double precision,
  "SPY_s1_upper" double precision,
  "SPY_s1_lower" double precision,
  "SPY_risk_upper" double precision,
  "SPY_risk_lower" double precision,
  "SPY_s2_upper" double precision,
  "SPY_s2_lower" double precision,
  "SPY_s3_upper" double precision,
  "SPY_s3_lower" double precision,
  "SPY_s1_pct" double precision,
  "SPY_s2_pct" double precision,
  "VIX_close_prev" double precision,
  "VIX_center" double precision,
  "VIX_s1_upper" double precision,
  "VIX_s1_lower" double precision,
  "VIX_risk_upper" double precision,
  "VIX_risk_lower" double precision,
  "VIX_s2_upper" double precision,
  "VIX_s2_lower" double precision,
  "VIX_s3_upper" double precision,
  "VIX_s3_lower" double precision,
  "VIX_s1_pct" double precision,
  "VIX_s2_pct" double precision,
  "IWM_close_prev" double precision,
  "IWM_center" double precision,
  "IWM_s1_upper" double precision,
  "IWM_s1_lower" double precision,
  "IWM_risk_upper" double precision,
  "IWM_risk_lower" double precision,
  "IWM_s2_upper" double precision,
  "IWM_s2_lower" double precision,
  "IWM_s3_upper" double precision,
  "IWM_s3_lower" double precision,
  "IWM_s1_pct" double precision,
  "IWM_s2_pct" double precision,
  "QQQ_close_prev" double precision,
  "QQQ_center" double precision,
  "QQQ_s1_upper" double precision,
  "QQQ_s1_lower" double precision,
  "QQQ_risk_upper" double precision,
  "QQQ_risk_lower" double precision,
  "QQQ_s2_upper" double precision,
  "QQQ_s2_lower" double precision,
  "QQQ_s3_upper" double precision,
  "QQQ_s3_lower" double precision,
  "QQQ_s1_pct" double precision,
  "QQQ_s2_pct" double precision,
  "added_at" text
);

create table if not exists weekly_posts (
  "id" bigint primary key,
  "date" text,
  "post_id" text,
  "filename" text,
  "weekly_centroid" double precision,
  "weekly_centroid_is_range" bigint,
  "net_zero_speed" double precision,
  "weekly_downside_pivot" double precision,
  "weekly_upside_pivot" double precision,
  "reversion_prob" double precision,
  "reversion_target" double precision,
  "fly_pattern" text,
  "sentiment_regime" text,
  "vix_pin" double precision,
  "momentum_threshold" double precision,
  "SPX_weekly_upper" double precision,
  "SPX_weekly_lower" double precision,
  "SPX_weekly_moe" double precision,
  "ES_weekly_upper" double precision,
  "ES_weekly_lower" double precision,
  "ES_weekly_moe" double precision,
  "SPY_weekly_upper" double precision,
  "SPY_weekly_lower" double precision,
  "SPY_weekly_moe" double precision,
  "VIX_weekly_upper" double precision,
  "VIX_weekly_lower" double precision,
  "VIX_weekly_moe" double precision,
  "IWM_weekly_upper" double precision,
  "IWM_weekly_lower" double precision,
  "IWM_weekly_moe" double precision,
  "QQQ_weekly_upper" double precision,
  "QQQ_weekly_lower" double precision,
  "QQQ_weekly_moe" double precision,
  "added_at" text,
  "weekly_upside_target" double precision,
  "weekly_downside_target" double precision,
  "exclude_from_backtest" bigint,
  "exclude_reason" text
);

create table if not exists market_data (
  "id" bigint primary key,
  "date" text,
  "spx_open" double precision,
  "spx_high" double precision,
  "spx_low" double precision,
  "spx_close" double precision,
  "spx_prev_close" double precision,
  "spx_gap_pct" double precision,
  "vix_open" double precision,
  "vix_high" double precision,
  "vix_low" double precision,
  "vix_close" double precision,
  "vix_prev_close" double precision,
  "vix_gap_pct" double precision,
  "added_at" text
);

create table if not exists rules (
  rule_id text primary key,
  scope text,
  category text,
  statement text,
  condition text,
  prediction text,
  historical_rate double precision,
  sample_size bigint,
  out_of_sample_rate double precision,
  out_of_sample_n bigint,
  confidence_tier text,
  action_guidance text,
  last_backtest_date text
);